
[workspace]
resolver = "2"
members = [
    "pbr_core",
    "pbr_gui",
]

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.pbr_core]
opt-level = 3

[profile.dev.package.pbr_gui]
opt-level = 3

